### ISSUE TITLE
Change Reference System

### ISSUE THREAD

**Issue by sluetze** [sig-bsi-grundschutz/content#59]
Change controls file to utilize the automatic referencing

**Comment by sluetze** [comment]
done in https://github.com/sig-bsi-grundschutz/content/commit/57ac7d0b2950661db5d3ba48b7cd3f219a74ee44

but waiting for https://github.com/ComplianceAsCode/content/pull/12165

**Comment by benruland** [comment]
The referenced MR is now done as well.

I would consider this issue done.
